apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-api.fullname" . }}-config
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: "{{ $value }}"
{{- end }}